# Generated by Django 4.2.3 on 2023-08-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='del_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
